{{- if and .Values.rbac.create (eq .Values.rbac.customClusterRole.enabled false) -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "helm-release-viewer.labels" . | nindent 4 }}
  name: {{ .Values.nameOverride }}-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
  {{- if .Values.rbac.readOnly }}
    verbs: ["get", "list", "watch"]
  {{- else }}
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  {{- end }}
{{- end }}

