apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "helm-release-viewer.labels" . | nindent 4 }}
  {{- if .Values.deployment.annotations }}
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:  
    {{- .Values.deployment.selectorLabels | toYaml | nindent 6 }}
  template:
    metadata:
      labels:
        {{- .Values.deployment.selectorLabels | toYaml | nindent 8 }}
        {{- if .Values.azureWorkloadIdentity.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
      annotations:
        {{- toYaml .Values.deployment.podAnnotations | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy | default "IfNotPresent" }}
        env:
        - name: APP_PORT
          value: "{{ .Values.deployment.ports.containerPort | default 8080}}"
        - name: LOG_LEVEL
          value: {{ .Values.app.logLevel | default "info"}}  
        - name: TIMEOUT
          value: "{{ .Values.app.timeout | default "120" }}"        
        {{- if .Values.deployment.additionalEnvs }}
          {{- toYaml .Values.deployment.additionalEnvs | nindent 8 }}
        {{- end }}
        {{- if .Values.deployment.envFrom }}
        envFrom:
          {{- toYaml .Values.deployment.envFrom | nindent 8 }}
        {{- end }}
        {{- if .Values.deployment.securityContext }}
        securityContext:
          {{- toYaml .Values.deployment.securityContext | nindent 10 }}
        {{- end }}       
        {{- if .Values.deployment.resources }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        {{- end }}
        ports:
        - name: {{ .Values.deployment.ports.name | default "http"}}
          containerPort: {{ .Values.deployment.ports.containerPort | default 8080}}
          protocol: {{ .Values.deployment.ports.protocol | default "TCP"}}
        {{- if .Values.deployment.volumeMounts }}
        volumeMounts:
          {{- toYaml .Values.deployment.volumeMounts | nindent 8 }}
        {{- end }}
        {{- if .Values.deployment.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.deployment.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.deployment.readinessProbe | nindent 10 }}
        {{- end }}
      {{- if .Values.deployment.volumes }}
      volumes:
        {{- toYaml .Values.deployment.volumes | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Name }}
      {{- if .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.deployment.topologySpreadConstraints | nindent 8 }}
      {{- end }}
