{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helm-release-viewer.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-release-viewer.labels" . | nindent 4 }}  
spec:
  {{- .Values.podDisruptionBudget.spec | toYaml | nindent 2 }}
  selector:
    matchLabels:
    {{- .Values.deployment.selectorLabels | toYaml | nindent 6 }}
{{- end -}}