{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-release-viewer.labels" . | nindent 4 }}
    {{- if .Values.azureWorkloadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
  annotations:
  {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.azureWorkloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.azureWorkloadIdentity.clientID }}
  {{- end }}
{{- end }}
