{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default .Values.deployment.name }}
  labels:
    {{- include "helm-release-viewer.labels" . | nindent 4 }}
    {{- .Values.deployment.selectorLabels | toYaml | nindent 4}}
spec:
  selector:
    {{- .Values.deployment.selectorLabels | toYaml | nindent 4}}
  ports:
  - name: {{ .Values.deployment.ports.name | default "http" }}
    port: {{ .Values.service.port | default 80  }}
    targetPort: {{ .Values.deployment.ports.containerPort | default 8080 }}
    protocol: {{ .Values.deployment.ports.protocol | default "TCP" }}
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- end  }}